dofile("./AI/USER_AI/RNAI_MAI/Const.lua")
dofile("./AI/USER_AI/RNAI_MAI/SkillData.lua")
dofile("./AI/USER_AI/RNAI_MAI/HomCfg.lua")
dofile("./AI/USER_AI/RNAI_MAI/Geo.lua")
dofile("./AI/USER_AI/RNAI_MAI/tablelib.lua")
dofile("./AI/USER_AI/RNAI_MAI/MapInfo.lua")
dofile("./AI/USER_AI/RNAI_MAI/Main.lua")
